<?php

/**
 * Implementation of hook_feeds_node_processor_targets_alter().
 */
function feeds_user_signature_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  if ($entity_type == 'user') {
    $targets['signature'] = array(
      'name' => t('User Signature'),
      'description' => t("A Drupal user's Signature"),
      'callback' => 'feeds_user_signature_set_target', // See 2)
    );
  }
}

/**
 * Callback for mapping. Here is where the actual mapping happens.
 */
function feeds_user_signature_set_target($source, $entity, $target, $value) {
  if(empty($value)){
    return;
  }
  $entity->signature = $value;
}